name: main
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run affected:lint

      - name: Test
        run: npm test
